name: Run pdflatex
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/rafaelnsantos/devcontainer-latex:ubuntu22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        env:
          GIT_SSL_NO_VERIFY: true

      - name: Compile LaTeX document
        run: |
          latexmk -pdf -interaction=nonstopmode -file-line-error main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: main.pdf
          path: .

      - name: Create Release and Upload PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}